### Get All Messages
GET http://localhost:3000/messages

### Post Message

POST http://localhost:3000/messages
content-type: application/json

{
    "content": "message after adding di"
}

### Get Message
GET http://localhost:3000/messages/965